In [ ]:
from osgeo import gdal
from osgeo.gdalconst import *
import os, sys

os.chdir('../Exercise2-todeliver/data')

In [ ]:
import fiona
c=fiona.open('GSHHS_c.shp','r')
c.closed

In [ ]:
next(c)

In [ ]:
len(list(c))

In [ ]:
c=fiona.open('GSHHS_c.shp','r')
len(list(c))

In [ ]:
c.close()
c.closed

In [ ]:
try:
    with fiona.open('GSHHS_c.shp') as c:
        print(len(list(c)))
except:
    print(c.closed)

In [ ]:
gdal.AllRegister()

In [ ]:
driver=gdal.GetDriverByName('HFA')
driver.Register()

In [ ]:
driver=gdal.GetDriverByName('GeoTiff')
driver==None

In [ ]:
drv_count=gdal.GetDriverCount()
drv_count

In [ ]:
for idx in range(10):
    driver=gdal.GetDriver(idx)
    print("%10s: %s"%(driver.ShortName, driver.LongName))

In [1]:
from osgeo import gdal
from osgeo.gdalconst import *
import os, sys
os.chdir('../Exercise3-todeliver/data-Exercise3')
dataset=gdal.Open("geotiff_file.tif")

d:\learnpy\learnOpengis-1\.venv\Lib\site-packages\osgeo\gdal.py:311: FutureWarning: Neither gdal.UseExceptions() nor gdal.DontUseExceptions() has been explicitly called. In GDAL 4.0, exceptions will be enabled by default.
  warnings.warn(


In [3]:
dataset.GetDescription()

'geotiff_file.tif'

In [4]:
dataset.RasterCount

3

In [5]:
dataset.RasterXSize

1500

In [6]:
dataset.RasterYSize

900

In [7]:
dataset.GetGeoTransform()

(1868454.913, 30.0, 0.0, 5353126.266, 0.0, -30.0)

In [8]:
dataset.GetMetadata()

{'AREA_OR_POINT': 'Area', 'PyramidResamplingType': 'NEAREST'}

In [9]:
dataset1=gdal.Open("lu75c.tif")
dataset1.GetMetadata()

{'TIFFTAG_XRESOLUTION': '1',
 'TIFFTAG_YRESOLUTION': '1',
 'AREA_OR_POINT': 'Area'}

In [10]:
dataset.RasterCount

3

In [11]:
mds=gdal.Open("MOD09A1.A2009193.h28v06.005.2009203125525.hdf")
mds.RasterCount

0

In [12]:
mds1=mds.GetSubDatasets()
len(mds1)

13

In [13]:
mds1[0]

('HDF4_EOS:EOS_GRID:"MOD09A1.A2009193.h28v06.005.2009203125525.hdf":MOD_Grid_500m_Surface_Reflectance:sur_refl_b01',
 '[2400x2400] sur_refl_b01 MOD_Grid_500m_Surface_Reflectance (16-bit integer)')

In [14]:
mds1[12]

('HDF4_EOS:EOS_GRID:"MOD09A1.A2009193.h28v06.005.2009203125525.hdf":MOD_Grid_500m_Surface_Reflectance:sur_refl_day_of_year',
 '[2400x2400] sur_refl_day_of_year MOD_Grid_500m_Surface_Reflectance (16-bit unsigned integer)')

In [15]:
band=dataset.GetRasterBand(1)   #Get the band object by passing the band index to the Dataset's GetRasterBand() method
dataset.RasterCount

3

In [16]:
img_width,img_height = dataset.RasterXSize,dataset.RasterYSize
img_width,img_height

(1500, 900)

In [17]:
#左上角点坐标(padfGeoTransform[0],padfGeoTransform[3])
#GeoTransform[1]是像元宽度(影像在宽度上的分辨率)；
#GeoTransform[5]是像元高度(影像在高度上的分辨率)；
#如果影像是指北的,padfGeoTransform[2]和padfGeoTransform[4]这两个参数的值为0。
dataset.GetGeoTransform()

(1868454.913, 30.0, 0.0, 5353126.266, 0.0, -30.0)

In [18]:
dataset.GetProjection()

'PROJCS["Albers_Beijing54",GEOGCS["Unknown datum based upon the Krassowsky 1940 ellipsoid",DATUM["Not_specified_based_on_Krassowsky_1940_ellipsoid",SPHEROID["Krassowsky 1940",6378245,298.3,AUTHORITY["EPSG","7024"]],AUTHORITY["EPSG","6024"]],PRIMEM["Greenwich",0],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]]],PROJECTION["Albers_Conic_Equal_Area"],PARAMETER["latitude_of_center",0],PARAMETER["longitude_of_center",105],PARAMETER["standard_parallel_1",25],PARAMETER["standard_parallel_2",47],PARAMETER["false_easting",0],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Easting",EAST],AXIS["Northing",NORTH]]'

In [19]:
dataset1.RasterCount

1

In [20]:
band1=dataset1.GetRasterBand(1)
dir(band1)[:6]+dir(band1)[-3:]

['AdviseRead',
 'AsMDArray',
 'Checksum',
 'ComputeBandStats',
 'ComputeRasterMinMax',
 'ComputeStatistics',
 '_parent_ds',
 'this',
 'thisown']

In [21]:
band1.XSize

6122

In [22]:
band1.YSize

4669

In [23]:
band1.DataType

3

In [24]:
band1.GetNoDataValue()

In [25]:
dataset2=gdal.Open("lu75i1.tif")
dataset2.GetMetadata()
dataset2.RasterCount

1

In [26]:
band2=dataset2.GetRasterBand(1)
band2.GetNoDataValue()

255.0

In [27]:
band2.GetMaximum()
band2.GetMinimum()
band2.ComputeRasterMinMax()

(0.0, 18.0)

In [28]:
band3=dataset2.GetRasterBand(1)
band3.GetMaximum()
band3.GetMinimum()

In [29]:
from osgeo import gdalconst
dir(gdalconst)

['CE_Debug',
 'CE_Failure',
 'CE_Fatal',
 'CE_None',
 'CE_Warning',
 'CPLES_BackslashQuotable',
 'CPLES_CSV',
 'CPLES_SQL',
 'CPLES_SQLI',
 'CPLES_URL',
 'CPLES_XML',
 'CPLES_XML_BUT_QUOTES',
 'CPLE_AWSAccessDenied',
 'CPLE_AWSBucketNotFound',
 'CPLE_AWSInvalidCredentials',
 'CPLE_AWSObjectNotFound',
 'CPLE_AWSSignatureDoesNotMatch',
 'CPLE_AppDefined',
 'CPLE_AssertionFailed',
 'CPLE_FileIO',
 'CPLE_HttpResponse',
 'CPLE_IllegalArg',
 'CPLE_NoWriteAccess',
 'CPLE_None',
 'CPLE_NotSupported',
 'CPLE_ObjectNull',
 'CPLE_OpenFailed',
 'CPLE_OutOfMemory',
 'CPLE_UserInterrupt',
 'CXT_Attribute',
 'CXT_Comment',
 'CXT_Element',
 'CXT_Literal',
 'CXT_Text',
 'DCAP_COORDINATE_EPOCH',
 'DCAP_CREATE',
 'DCAP_CREATECOPY',
 'DCAP_CREATECOPY_MULTIDIMENSIONAL',
 'DCAP_CREATE_FIELD',
 'DCAP_CREATE_LAYER',
 'DCAP_CREATE_MULTIDIMENSIONAL',
 'DCAP_CURVE_GEOMETRIES',
 'DCAP_DEFAULT_FIELDS',
 'DCAP_DELETE_FIELD',
 'DCAP_DELETE_LAYER',
 'DCAP_FEATURE_STYLES',
 'DCAP_FEATURE_STYLES_READ',
 'DCAP_FEATURE_S

In [30]:
from osgeo import gdalconst
dataset = gdal.Open('geotiff_file.tif') 
band = dataset.GetRasterBand(1)
band.DataType

1

In [31]:
import array
from numpy import *
dataset=gdal.Open("lu75c.tif")
dataset.ReadAsArray(2500,2500,100,100)
data=dataset.ReadAsArray(2500,2500,100,100)

In [32]:
dataset.ReadRaster(2500,2500,100,100)

bytearray(b'\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00@\x00@\x00@\x00@\x00@\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0

In [33]:
value=data[42,94]  # read the pixel in the 95th column and 43rd row
value

np.int16(11)

In [34]:
from osgeo import gdal
dataset1 = gdal.Open("geotiff_file.tif")
band = dataset1.GetRasterBand(1)
band.ReadAsArray(100,100,5,5,10,10)

array([[236, 236, 237, 237, 237, 237, 237, 237, 227, 227],
       [236, 236, 237, 237, 237, 237, 237, 237, 227, 227],
       [235, 235, 232, 232, 233, 233, 234, 234, 225, 225],
       [235, 235, 232, 232, 233, 233, 234, 234, 225, 225],
       [242, 242, 235, 235, 232, 232, 233, 233, 224, 224],
       [242, 242, 235, 235, 232, 232, 233, 233, 224, 224],
       [254, 254, 244, 244, 238, 238, 237, 237, 229, 229],
       [254, 254, 244, 244, 238, 238, 237, 237, 229, 229],
       [246, 246, 246, 246, 248, 248, 250, 250, 235, 235],
       [246, 246, 246, 246, 248, 248, 250, 250, 235, 235]], dtype=uint8)

In [35]:
dir(band)

['AdviseRead',
 'AsMDArray',
 'Checksum',
 'ComputeBandStats',
 'ComputeRasterMinMax',
 'ComputeStatistics',
 'CreateMaskBand',
 'DataType',
 'DeleteNoDataValue',
 'Fill',
 'FlushCache',
 'GetActualBlockSize',
 'GetBand',
 'GetBlockSize',
 'GetCategoryNames',
 'GetColorInterpretation',
 'GetColorTable',
 'GetDataCoverageStatus',
 'GetDataset',
 'GetDefaultHistogram',
 'GetDefaultRAT',
 'GetDescription',
 'GetHistogram',
 'GetMaskBand',
 'GetMaskFlags',
 'GetMaximum',
 'GetMetadata',
 'GetMetadataDomainList',
 'GetMetadataItem',
 'GetMetadata_Dict',
 'GetMetadata_List',
 'GetMinimum',
 'GetNoDataValue',
 'GetNoDataValueAsInt64',
 'GetNoDataValueAsUInt64',
 'GetOffset',
 'GetOverview',
 'GetOverviewCount',
 'GetRasterCategoryNames',
 'GetRasterColorInterpretation',
 'GetRasterColorTable',
 'GetSampleOverview',
 'GetScale',
 'GetStatistics',
 'GetTiledVirtualMem',
 'GetTiledVirtualMemArray',
 'GetUnitType',
 'GetVirtualMem',
 'GetVirtualMemArray',
 'GetVirtualMemAuto',
 'GetVirtualMemAuto

In [ ]:
from osgeo import gdal
import numpy
dataset = gdal.Open("geotiff_file.tif")
band2 = dataset.GetRasterBand(2)
band3 = dataset.GetRasterBand(3)
cols = 100
rows = 100
data2 = band2.ReadAsArray(0, 0, cols,rows).astype(numpy.float16)
data3 = band3.ReadAsArray(0, 0, cols,rows).astype(numpy.float16)
mask = numpy.greater(data3 + data2, 0)   #判断data3+data2是否大于0
ndvi = numpy.choose(mask, (-99, (data3 - data2) / (data3 + data2)))
# mask,(choice1,choice2)


C:\Users\jrs16\AppData\Local\Temp\ipykernel_28376\1125455267.py:11: RuntimeWarning: invalid value encountered in divide
  ndvi = numpy.choose(mask, (-99, (data3 - data2) / (data3 + data2)))


In [37]:
ndvi

array([[0.2766, 0.318 , 0.4285, ..., 0.3057, 0.275 , 0.6   ],
       [0.1951, 0.2208, 0.3135, ..., 0.2683, 0.3538, 1.    ],
       [0.2142, 0.2195, 0.2896, ..., 0.4182, 0.758 , 1.    ],
       ...,
       [0.6313, 0.6113, 0.6553, ..., 0.3333, 0.359 , 0.36  ],
       [0.4119, 0.4119, 0.422 , ..., 0.3784, 0.3784, 0.3418],
       [0.3684, 0.322 , 0.309 , ..., 0.4084, 0.4   , 0.3684]],
      shape=(100, 100), dtype=float16)

In [38]:
False in mask

True

In [39]:
fn='aster.img'
ds=gdal.Open(fn,GA_ReadOnly)
if ds is None:
    print('Could not open '+fn)
    sys.exit(1)

In [ ]:
cols=ds.RasterXSize
rows=ds.RasterYSize
bands=ds.RasterCount
print(cols,rows,bands)


5665 5033 3


In [41]:
geotransform=ds.GetGeoTransform()
originX=geotransform[0]
originY=geotransform[3]
pixelWidth=geotransform[1]
pixelHeight=geotransform[5]

In [53]:
aster_band1 = ds.GetRasterBand(1)
data1 = aster_band1.ReadAsArray(0, 0, cols, rows).astype(numpy.float16)
mask = data1 > 0
average = data1[:].mean()
average_over0 = data1[mask].mean()


In [59]:
print(f"over0:{average:.2f}")

over0:47.56


In [58]:
print(f"over0:{average_over0:.2f}")

over0:76.31


In [42]:
from osgeo import gdal
format = "GTiff"
driver = gdal.GetDriverByName( format )
metadata = driver.GetMetadata()
if (gdal.DCAP_CREATE in metadata) and metadata[DCAP_CREATE]: 
    print ('Driver %s supports Create() method.' % format)
if (gdal.DCAP_CREATECOPY in metadata) and metadata[DCAP_CREATE]:
    print ('Driver %s supports CreateCopy() method.' % format)



Driver GTiff supports Create() method.
Driver GTiff supports CreateCopy() method.


In [43]:
src_filename = "geotiff_file.tif"
dst_filename = "xx_geotiff_copy.tif"
driver = gdal.GetDriverByName('GTiff')
src_ds = gdal.Open(src_filename)
dst_ds = driver.CreateCopy(dst_filename,src_ds, 0 )


In [44]:
driver.CreateCopy("sd.tif",dataset,0,['TILED=YES','COMPRESS=PACKBITS'])

<osgeo.gdal.Dataset; proxy of <Swig Object of type 'GDALDatasetShadow *' at 0x00000175634D56E0> >

In [45]:
data3

array([[30., 29., 25., ..., 47., 51., 28.],
       [49., 47., 44., ..., 52., 44., 21.],
       [51., 50., 49., ..., 39., 29., 18.],
       ...,
       [31., 29., 24., ..., 56., 53., 51.],
       [36., 36., 32., ..., 51., 51., 53.],
       [39., 39., 36., ..., 50., 49., 52.]],
      shape=(100, 100), dtype=float16)

In [46]:
help(driver.Create)

Help on method Create in module osgeo.gdal:

Create(*args, **kwargs) method of osgeo.gdal.Driver instance
    Create(Driver self, char const * utf8_path, int xsize, int ysize, int bands=1, GDALDataType eType=GDT_Byte, char ** options=None) -> Dataset


    Create a new :py:class:`Dataset` with this driver.
    See :cpp:func:`GDALDriver::Create`.

    Parameters
    ----------
    utf8_path : str
       Path of the dataset to create.
    xsize : int
       Width of created raster in pixels. Set to zero for vector datasets.
    ysize : int
       Height of created raster in pixels. Set to zero for vector datasets.
    bands : int, default = 1
        Number of bands. Set to zero for vector datasets.
    eType : int, default = :py:const:`GDT_Byte`
        Raster data type. Set to :py:const:`GDT_Unknown` for vector datasets.
    options : list/dict
        List of driver-specific options

    Returns
    -------
    Dataset

    Examples
    --------
    >>> with gdal.GetDriverByName('GTif

In [47]:
driver = gdal.GetDriverByName( 'GTiff' )
dst_filename = 'x_tmp.tif'
dst_ds = driver.Create(dst_filename, xsize=512, ysize=512, bands=1, eType=gdal.GDT_Byte)

In [48]:
import numpy
from osgeo import osr
dst_ds.SetGeoTransform( [ 444720, 30, 0, 3751320, 0, -30 ] )
srs = osr.SpatialReference()
srs.SetUTM(11,True )
srs.SetWellKnownGeogCS( 'WGS84' )
dst_ds.SetProjection( srs.ExportToWkt() )
raster = numpy.zeros( (512, 512) )
dst_ds.GetRasterBand(1).WriteArray(raster)

0

In [50]:
from osgeo import gdal
import numpy
dataset = gdal.Open("geotiff_file.tif")
width = dataset.RasterXSize
height = dataset.RasterYSize
datas = dataset.ReadAsArray(0,0,width,height)
driver = gdal.GetDriverByName("GTiff")
tods = driver.Create("x_geotiff_file_3.tif",width,height,3,options=["INTERLEAVE=PIXEL"]) 
tods.WriteRaster(0,0,width,height,datas.tobytes(),width,height, band_list=[1,2,3])

0